global using Ebla.Web;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Ebla.Web.Models;
global using System.ComponentModel.DataAnnotations;
global using Ebla.Web.Services;
global using Microsoft.AspNetCore.Components;
global using System.Net.Http.Json;
global using Microsoft.JSInterop;